swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User transactions API
      description: API for fetching user's transactions of the month
      parameters:
        - in: path
          name : accountId
          description: id of the account
          required: true
          type: string
      #produces:
       # - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/TransactionResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/TransactionResponse'
        '500':
          description: Internal Server Error
  /accounts/{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User transactions API
      description: API for fetching details of a transaction
      parameters:
        - in: path
          name : accountId
          description: id of the account
          required: true
          type: string
        - in: path
          name : transactionId
          description: id of the transaction
          required: true
          type: string
      #produces:
       # - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/TransactionResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/TransactionResponse'
        
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User transactions API
      description: API for updating a transaction details
      parameters:
        - in: path
          name : accountId
          description: id of the account
          required: true
          type: string
        - in: path
          name : transactionId
          description: id of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UserTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/TransactionResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/TransactionResponse'
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
          type:
            type: string
          category:
            type: string
          note:
            type: string
  UserTransactions:
    properties:
      date:
        type: string
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: amount of transaction
      balance:
        type: number
        description: balance after transaction
      type:
        type: string
        description: type of transaction
      category:
        type: string
        description: category of transaction
      note:
        type: string
        description: note of transaction